### ISSUE TITLE
メンバー集める

### ISSUE THREAD

**Issue by mactkg** [post-internet/about#1]
噂によると20人必要らしい
- [ ] @mactkg
- [ ] @kvvzr 
- [ ] @3846masa

**Comment by kvvzr** [comment]
- 部長どうするのか問題
- 顧問どうするのか問題

**Comment by shisoAqron** [comment]
今slackに参加・招待されているのは7人だけど残りのメンバーを集めなくてはいけない

**Comment by mactkg** [comment]
19人まで来た

**Comment by mactkg** [comment]
チャットには24人居るのでどうにかなる、とりあえず問題はなさそうなのでクローズします
