### ISSUE TITLE
事務室に聞きたい情報

### ISSUE THREAD

**Issue by mactkg** [post-internet/about#2]
- 部室とかの運用
- 申し込み期間などはあるのか

**Comment by shisoAqron** [comment]
@mactkg 大学のページにありました。
公認サークルの手続きは5月ごろだそうです。
http://www.meiji.ac.jp/campus/circle/6t5h7p00000g8e3l.html

**Comment by mactkg** [comment]
@ShisoAqron なるほど！これは便利。それまでの間の活動とかも考えたほうが良さそう。

**Comment by mactkg** [comment]
12月に設立チャンスあるとのこと

**Comment by mactkg** [comment]
事務に問い合わせたのでクローズ
