### ISSUE TITLE
サークル名を決める

### ISSUE THREAD

**Issue by kvvzr** [post-internet/about#4]
# サークル名について
## どういうのが良いのか
- 外部に説明しやすい
- ぐぐりやすさがそれなりにあること
## 現在の案
- Nakano Computer Club (NCC)
- Undefined

案をどんどんコメントしていって欲しいです

**Comment by kvvzr** [comment]
- Nakano Central Computer Club (NCCC)
- Sunmall Computer Club (SCC)
- Broadway Computer Club (BCC)

**Comment by salmoncode** [comment]
Computer Tips Club
Frontier Engineer Club

中野に依存してるイメージがあまりないので

**Comment by kvvzr** [comment]
Frontier Engineer Club、恐れ多くないすか...

中野に依存しているイメージ、僕もない
感で物を言っているけど、例えばコンテストに出た時に明治大学 Meiji Computer Clubより、明治大学 Nakano Computer Clubって言われたほうが良くないですかってくらい

**Comment by kvvzr** [comment]
## ぐぐりやすさについて

基本的には略称で呼ばれると思うので(偏見)、`明治 略称`で検索する気がする(偏見)
そういった意味ではMCCでもNCCでもどちらでも良いのでは。ただ、他大学のサークル略称とはあまりコンフリクトしたくない

## 地名を使うことについて

> 中野キャンパスでずっと活動してるとは限らないと思うのでNCCは... (Twitterより)

確かにそうだけど、活動方針による。キャンパス間を纏める力があればやってもいい。
生田のほうが強い人が居る印象なので一緒に活動できるのは良いと思う。でも生田の強い人、向こうのこういうサークルに入ってそう(偏見)
