### ISSUE TITLE
週間・年間の予定をたてる

### ISSUE THREAD

**Issue by mactkg** [post-internet/about#9]
- [ ] 週間活動予定表
- [ ] 年間行事予定表

何をやりましょうか。ということもざっくり決めたい。そもそも特別決めるようなこともなさそうだけれども、目標にする大会とかあっても良さそう。多分月1くらいのイベントはやる気がする。

**Comment by mactkg** [comment]
12月にアドベントカレンダーやるというイベントがあってもおもしろいと思いついた

**Comment by 3846masa** [comment]
http://www.adventar.org/
こういうサービスがある
Qiitaはちゃんと技術系でないと消されるらしい...
http://qiita.com/advent-calendar/2014
